services:
  book-portal-be:
    build: ./book-portal-be
    platform: linux/amd64
    container_name: "book-portal-be"

  book-portal-fe:
    build: ./book-portal-fe
    platform: linux/amd64
    container_name: "book-portal-fe"
    depends_on:
      - book-portal-be
  proxy:
    build: ./nginx
    platform: linux/amd64
    container_name: "book-portal-proxy"
    restart: always
    ports:
      - "80:80"
